services:
  linkstack:
    build:
      context: .
      dockerfile: Dockerfile
    image: linkstack-rafael:latest
    restart: unless-stopped
    environment:
      HTTP_SERVER_NAME: link.rafaelmarcolino.online
      HTTPS_SERVER_NAME: link.rafaelmarcolino.online
      SERVER_ADMIN: admin@rafaelmarcolino.online
      TZ: America/Sao_Paulo
    expose:
      - "80"
    volumes:
      - linkstack_data:/htdocs

volumes:
  linkstack_data: